bamboo:
  image: cptactionhank/atlassian-bamboo
  ports:
    - "8085:8085"
  volumes:
    - "./docker/bamboo:/var/atlassian/bamboo"

aut:
  build: ./dockerFiles/oracle-java8
  container_name: petclinic-aut
  ports:
    - "8080:8080"
  volumes:
    - "./docker/automation:/data"
