#
# Oracle Java 8 Dockerfile
#
# https://github.com/dockerfile/java
# https://github.com/dockerfile/java/tree/master/oracle-java8
#

# Pull base image.
FROM java:openjdk-8u92-jre-alpine

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["sh"]
